// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {models} from '../models';

export function CreateProject(arg1:number,arg2:dto.ProjectCreate):Promise<string>;

export function GetProjectsBySearchName(arg1:string):Promise<Array<models.Project>>;

export function MaskAsDone(arg1:number,arg2:number):Promise<string>;
