// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3) {
  return window['go']['controllers']['ProjectController']['AddTask'](arg1, arg2, arg3);
}

export function CreateProject(arg1, arg2) {
  return window['go']['controllers']['ProjectController']['CreateProject'](arg1, arg2);
}

export function DeleteProject(arg1, arg2) {
  return window['go']['controllers']['ProjectController']['DeleteProject'](arg1, arg2);
}

export function DeleteTask(arg1, arg2) {
  return window['go']['controllers']['ProjectController']['DeleteTask'](arg1, arg2);
}

export function GetAllProjects() {
  return window['go']['controllers']['ProjectController']['GetAllProjects']();
}

export function GetById(arg1) {
  return window['go']['controllers']['ProjectController']['GetById'](arg1);
}

export function GetFromUser(arg1) {
  return window['go']['controllers']['ProjectController']['GetFromUser'](arg1);
}

export function GetProjectsBySearchName(arg1) {
  return window['go']['controllers']['ProjectController']['GetProjectsBySearchName'](arg1);
}

export function GetWithUserById(arg1) {
  return window['go']['controllers']['ProjectController']['GetWithUserById'](arg1);
}

export function MarkAsDone(arg1, arg2) {
  return window['go']['controllers']['ProjectController']['MarkAsDone'](arg1, arg2);
}
