// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateAdmin(arg1:dto.UserRegister):Promise<boolean>;

export function GetUser(arg1:number):Promise<dto.UserDtoOut>;
