// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeEmail(arg1, arg2) {
  return window['go']['controllers']['UserController']['ChangeEmail'](arg1, arg2);
}

export function ChangeName(arg1, arg2) {
  return window['go']['controllers']['UserController']['ChangeName'](arg1, arg2);
}

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['controllers']['UserController']['ChangePassword'](arg1, arg2, arg3);
}

export function ChangeProfilePic(arg1, arg2) {
  return window['go']['controllers']['UserController']['ChangeProfilePic'](arg1, arg2);
}

export function CreateAdmin(arg1) {
  return window['go']['controllers']['UserController']['CreateAdmin'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['controllers']['UserController']['CreateUser'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['controllers']['UserController']['DeleteUser'](arg1);
}

export function GetAllUsers() {
  return window['go']['controllers']['UserController']['GetAllUsers']();
}

export function GetRecentUsers(arg1) {
  return window['go']['controllers']['UserController']['GetRecentUsers'](arg1);
}

export function GetUser(arg1) {
  return window['go']['controllers']['UserController']['GetUser'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['controllers']['UserController']['Login'](arg1, arg2);
}

export function SearchByName(arg1) {
  return window['go']['controllers']['UserController']['SearchByName'](arg1);
}

export function UpdateRole(arg1, arg2) {
  return window['go']['controllers']['UserController']['UpdateRole'](arg1, arg2);
}
