// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAdmin(arg1) {
  return window['go']['controllers']['UserController']['CreateAdmin'](arg1);
}

export function GetUser(arg1) {
  return window['go']['controllers']['UserController']['GetUser'](arg1);
}
