// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {models} from '../models';
import {os} from '../models';

export function CreateUser(arg1:dto.UserRegister,arg2:boolean):Promise<boolean>;

export function GetById(arg1:number):Promise<models.User>;

export function UpdateProfilePicture(arg1:number,arg2:os.File):Promise<boolean>;
