// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1, arg2) {
  return window['go']['services']['UserService']['CreateUser'](arg1, arg2);
}

export function GetById(arg1) {
  return window['go']['services']['UserService']['GetById'](arg1);
}

export function UpdateProfilePicture(arg1, arg2) {
  return window['go']['services']['UserService']['UpdateProfilePicture'](arg1, arg2);
}
